# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/parallels/Desktop/riscv/riscvga/verilog/rvga/rvga.cache/wt [current_project]
set_property parent.project_path /home/parallels/Desktop/riscv/riscvga/verilog/rvga/rvga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo /home/parallels/Desktop/riscv/riscvga/verilog/rvga/rvga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/parallels/Desktop/riscv/riscvga/verilog/rvga_types.svh
  /home/parallels/Desktop/riscv/riscvga/verilog/debug_defines.svh
}
set_property file_type "Verilog Header" [get_files /home/parallels/Desktop/riscv/riscvga/verilog/rvga_types.svh]
set_property file_type "Verilog Header" [get_files /home/parallels/Desktop/riscv/riscvga/verilog/debug_defines.svh]
read_verilog -library xil_defaultlib -sv {
  /home/parallels/Desktop/riscv/riscvga/verilog/mux4.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/mux2.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/rfetch_stage.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/ifetch_stage.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/execute_stage.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/memory_stage.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/writeback_stage.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/decode_stage.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/rvga_top.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/dcache.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/icache.sv
  /home/parallels/Desktop/riscv/riscvga/verilog/array.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/parallels/Desktop/riscv/riscvga/verilog/rvga/rvga.srcs/constrs_1/new/zedboard_master.xdc
set_property used_in_implementation false [get_files /home/parallels/Desktop/riscv/riscvga/verilog/rvga/rvga.srcs/constrs_1/new/zedboard_master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top rvga_top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rvga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rvga_top_utilization_synth.rpt -pb rvga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
